Update delete_all.yml

diff --git a/.github/workflows/delete_all.yml b/.github/workflows/delete_all.yml
--- a/.github/workflows/delete_all.yml
+++ b/.github/workflows/delete_all.yml
@@ -47,7 +47,7 @@ jobs:
           else
             for volume_id in $volume_ids; do
               echo "Deleting volume $volume_id..."
-              scw block volume delete volume-id=$volume_id zone=${{ secrets.SCW_DEFAULT_ZONE }} || echo "Failed to delete volume $volume_id. It may be in use."
+              scw block volume delete volume-id=$volume_id zone=fr-par-1 || echo "Failed to delete volume $volume_id. It may be in use."
             done
           fi
 
