Update deploy_network.yml

diff --git a/.github/workflows/deploy_network.yml b/.github/workflows/deploy_network.yml
--- a/.github/workflows/deploy_network.yml
+++ b/.github/workflows/deploy_network.yml
@@ -147,7 +147,7 @@ jobs:
         run: |
           echo "Waiting for Load Balancer IPs to be assigned..."
       
-          # Fonction pour attendre l'IP du LoadBalancer
+          # Fonction pour récupérer l'IP du Load Balancer
           get_lb_ip() {
             local svc_name=$1
             local namespace=$2
@@ -164,14 +164,16 @@ jobs:
               echo "Attempt $i/$retries: Waiting for $svc_name to get an IP..."
               sleep 30  # Attente entre chaque tentative
             done
-
-          echo "Error: $svc_name Load Balancer IP not found."
-          exit 1
+      
+            echo "Error: $svc_name Load Balancer IP not found."
+            exit 1
           }
-
+      
+          # Récupérer l'IP d'Istio
           get_lb_ip istio-ingressgateway istio-system
+      
+          # Récupérer l'IP NGINX
           get_lb_ip ingress-nginx-controller ingress-nginx
-
 
           echo "Istio Load Balancer IP: $istio_lb_ip"
           echo "NGINX Load Balancer IP: $nginx_lb_ip"
