Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -23,39 +23,25 @@ jobs:
           chmod 700 get_helm.sh
           ./get_helm.sh
 
+      # Install Scaleway CLI
       - name: Install Scaleway CLI
         run: |
           curl -s https://raw.githubusercontent.com/scaleway/scaleway-cli/master/scripts/get.sh | sh
           scw version
 
-      # Initialize Scaleway CLI with credentials
+      # Configure Scaleway CLI
       - name: Configure Scaleway CLI
         env:
           SCW_ACCESS_KEY: ${{ secrets.SCW_ACCESS_KEY }}
           SCW_SECRET_KEY: ${{ secrets.SCW_SECRET_KEY }}
-          SCW_DEFAULT_PROJECT_ID: ${{ secrets.SCW_PROJECT_ID }}
-          SCW_DEFAULT_ORGANIZATION_ID: ${{ secrets.SCW_PROJECT_ID }}  # Set this for compatibility
-          SCW_DEFAULT_REGION: fr-par
-          SCW_DEFAULT_ZONE: fr-par-1
+          SCW_PROJECT_ID: ${{ secrets.SCW_PROJECT_ID }}
         run: |
-          echo "Scaleway CLI configured with environment variables."
-
-      # Generate kubeconfig file with Scaleway CLI
-      - name: Configure kubeconfig
-        env:
-          SCW_ACCESS_KEY: ${{ secrets.SCW_ACCESS_KEY }}
-          SCW_SECRET_KEY: ${{ secrets.SCW_SECRET_KEY }}
-          SCW_DEFAULT_PROJECT_ID: ${{ secrets.SCW_PROJECT_ID }}
-          SCW_DEFAULT_ORGANIZATION_ID: ${{ secrets.SCW_PROJECT_ID }}  # Set this for compatibility
-        run: |
-          mkdir -p ~/.kube
-          cluster_id=$(scw k8s cluster list name=k8s-cluster --output json | jq -r '.[0].id')
-          if [ -n "$cluster_id" ]; then
-            scw k8s kubeconfig get $cluster_id > ~/.kube/config
-          else
-            echo "Kubernetes cluster ID not found."
-            exit 1
-          fi
+          scw init \
+          --access-key "$SCW_ACCESS_KEY" \
+          --secret-key "$SCW_SECRET_KEY" \
+          --project-id "$SCW_PROJECT_ID" \
+          --region fr-par \
+          --zone fr-par-1
 
       - name: Terraform Init
         working-directory: ./infra
@@ -72,3 +58,18 @@ jobs:
           TF_VAR_scw_secret_key: ${{ secrets.SCW_SECRET_KEY }}
           TF_VAR_scw_project_id: ${{ secrets.SCW_PROJECT_ID }}
         run: terraform apply -auto-approve
+
+      # Retrieve cluster ID and generate kubeconfig after Terraform apply
+      - name: Configure kubeconfig
+        env:
+          SCW_ACCESS_KEY: ${{ secrets.SCW_ACCESS_KEY }}
+          SCW_SECRET_KEY: ${{ secrets.SCW_SECRET_KEY }}
+          SCW_PROJECT_ID: ${{ secrets.SCW_PROJECT_ID }}
+        run: |
+          mkdir -p ~/.kube
+          cluster_id=$(scw k8s cluster list name=k8s-cluster --output json | jq -r '.[0].id')
+          if [[ -z "$cluster_id" || "$cluster_id" == "null" ]]; then
+            echo "Error: Kubernetes cluster ID not found or is not valid."
+            exit 1
+          fi
+          scw k8s kubeconfig get "$cluster_id" > ~/.kube/config
