Update deploy_helm.yml

diff --git a/.github/workflows/deploy_helm.yml b/.github/workflows/deploy_helm.yml
--- a/.github/workflows/deploy_helm.yml
+++ b/.github/workflows/deploy_helm.yml
@@ -39,17 +39,20 @@ jobs:
           SCW_DEFAULT_ZONE: fr-par-1
         run: echo "Scaleway CLI configured with environment variables."
 
-      - name: Configure kubeconfig with Hardcoded Cluster ID
+      - name: Configure kubeconfig
         env:
           SCW_ACCESS_KEY: ${{ secrets.SCW_ACCESS_KEY }}
           SCW_SECRET_KEY: ${{ secrets.SCW_SECRET_KEY }}
           SCW_PROJECT_ID: ${{ secrets.SCW_PROJECT_ID }}
         run: |
           mkdir -p ~/.kube
-          cluster_id="779a0601-f5c7-419c-b474-54f644feb465"  # Use the provided cluster_id for testing
+          # Retrieve the cluster ID by explicitly passing the organization and project ID
+          cluster_id=$(scw k8s cluster list name=k8s-cluster organization-id=${{ secrets.SCW_ORGANIZATION_ID }} project-id=${{ secrets.SCW_PROJECT_ID }} --output json | jq -r '.[0].id')
+          if [[ -z "$cluster_id" || "$cluster_id" == "null" ]]; then
+            echo "Error: Kubernetes cluster ID not found or is not valid."
+            exit 1
+          fi
           scw k8s kubeconfig get "$cluster_id" > ~/.kube/config
-
-
 
       # Install Falco using Helm on the Kubernetes cluster
       - name: Deploy Falco with Helm
