Update deploy_helm.yml

diff --git a/.github/workflows/deploy_helm.yml b/.github/workflows/deploy_helm.yml
--- a/.github/workflows/deploy_helm.yml
+++ b/.github/workflows/deploy_helm.yml
@@ -100,6 +100,19 @@ jobs:
           
           kubectl delete -k ./helm/wazuh-kubernetes/wazuh/
 
+      - name: List and Delete All PVCs
+        run: |
+          # Get all PVC names in the default namespace
+          pvc_names=$(kubectl get pvc -o jsonpath='{.items[*].metadata.name}')
+          
+          if [ -z "$pvc_names" ]; then
+            echo "No PVCs found."
+          else
+            for pvc_name in $pvc_names; do
+              echo "Deleting PVC $pvc_name..."
+              kubectl delete pvc "$pvc_name" || echo "Failed to delete PVC $pvc_name. It may be in use."
+            done
+          fi
 
       - name: Clean Up Kibana Resources
         continue-on-error: true
