Update restore_pvc.yml

diff --git a/.github/workflows/restore_pvc.yml b/.github/workflows/restore_pvc.yml
--- a/.github/workflows/restore_pvc.yml
+++ b/.github/workflows/restore_pvc.yml
@@ -4,7 +4,7 @@ on:
   workflow_dispatch:
 
 jobs:
-  restore_pvc:
+  deploy:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout repository
@@ -57,14 +57,10 @@ jobs:
           echo "Cluster ID: $cluster_id"
           scw k8s kubeconfig get "$cluster_id" > ~/.kube/config
 
-      - name: Clean Up
+      - name: Uninstall All Helm Charts
         continue-on-error: true
         run: |
-          if helm list -n default | grep -q 'elasticsearch'; then
-            helm uninstall elasticsearch --namespace default
-          else
-            echo "Elastic not installed in the default namespace."
-          fi
+          echo "Uninstalling Helm charts..."
 
           if helm list -n default | grep -q 'prometheus-operator'; then
             helm uninstall prometheus-operator --namespace default
@@ -78,10 +74,28 @@ jobs:
             echo "Logstash not installed in the default namespace."
           fi
 
+          if helm list -n default | grep -q 'falco'; then
+            helm uninstall falco --namespace default
+          else
+            echo "Falco not installed in the default namespace."
+          fi
+
           if helm list -n default | grep -q 'filebeat'; then
             helm uninstall filebeat --namespace default
           else
             echo "Filebeat not installed in the default namespace."
+          fi
+
+          if helm list -n default | grep -q 'elasticsearch'; then
+            helm uninstall elasticsearch --namespace default
+          else
+            echo "Elasticsearch not installed in the default namespace."
+          fi
+
+          if helm list -n istio-system | grep -q 'istiod'; then
+            helm uninstall istiod --namespace istio-system
+          else
+            echo "Istiod not installed in the istio-system namespace."
           fi
 
           if helm list -n default | grep -q 'kibana'; then
@@ -90,8 +104,22 @@ jobs:
           else
             echo "Kibana not installed in the default namespace."
           fi
+          
+          kubectl delete -k ./helm/wazuh-kubernetes/wazuh/
 
-          kubectl delete -f ./doctobobo/backend/mysql-deployment.yaml -n doctobobo
+      - name: List and Delete All PVCs
+        run: |
+          # Get all PVC names in the default namespace
+          pvc_names=$(kubectl get pvc -o jsonpath='{.items[*].metadata.name}')
+          
+          if [ -z "$pvc_names" ]; then
+            echo "No PVCs found."
+          else
+            for pvc_name in $pvc_names; do
+              echo "Deleting PVC $pvc_name..."
+              kubectl delete pvc "$pvc_name" || echo "Failed to delete PVC $pvc_name. It may be in use."
+            done
+          fi
 
       - name: Clean Up Kibana Resources
         continue-on-error: true
@@ -303,7 +331,21 @@ jobs:
           helm repo update
           helm install prometheus-operator prometheus-community/kube-prometheus-stack --namespace default
 
-      - name: redeploy other ressources
-        continue-on-error: true
+      - name: Deploy Falco
         run: |
-          kubectl apply -f ./doctobobo/backend/mysql-deployment.yaml -n doctobobo
+          helm repo add falcosecurity https://falcosecurity.github.io/charts
+          helm repo update
+          helm install falco falcosecurity/falco --namespace default -f ./helm/values-falco.yaml
+
+      - name: Deploy Istio
+        run: |
+          helm repo add istio https://istio-release.storage.googleapis.com/charts
+          helm repo update
+          kubectl create namespace istio-system || true
+          helm upgrade --install istio-base istio/base -n istio-system --create-namespace
+          helm upgrade --install istiod istio/istiod -f ./helm/values-istio.yaml -n istio-system
+          helm upgrade --install istio-ingress istio/gateway -n istio-system
+
+      - name: Deploy Wazuh
+        run: |
+          kubectl apply -k ./helm/wazuh-kubernetes/wazuh/
